/* eslint-disable */
if (typeof window.splmap == "undefined") {
  window.splmap = {
    lang: {}
  };
}
window.splmap.lang.es = {

  "veh_comp_tractor":                              "Tractor",
  "veh_comp_trailer1":                             "Remolque 1",
  "veh_comp_dolly":                                "Mu&ntilde;equita",
  "veh_comp_trailer2":                             "Remolque 2",

  "sensor_search_busy_getting_data_msg":           "Obtener datos",
  "sensor_search_last_reading":                    "&Uacute;ltima lectura",
  "sensor_search_sensor_timestamp":                "Marca de tiempo del sensor",
  "sensor_search_switchto_spltools_instruction":   "Ver en SpartanLync Tools",

  "splmap_alert_header":                           "Alerta SpartanLync",
  "splmap_service_started":                        "El servicio SpartanLync Map se inici&oacute; correctamente",
  "splmap_service_failed":                         "Error al iniciar el servicio SpartanLync Map",
  "splmap_veh_flying_msg":                         "Volando al veh&iacute;culo<br />'{veh}'",
  "splmap_veh_flying_loading_gps":                 "Carga de datos de GPS del veh&iacute;culo",
  "splmap_veh_flying_loading_gps_subtitle":        "para volar ....",
  "splmap_vehpanel_component_title":               "Componentes del veh&iacute;culo",
  "splmap_vehpanel_splsensors_btn_tooltip":        "Ver datos del sensor SpartanLync para este veh&iacute;culo",

  "splmap_tooltip_map_add_veh_tofilter":           "Agregar dispositivo al filtro de veh&iacute;culos",
  "splmap_tooltip_vehtab_veh_flyto":               "Volar al veh&iacute;culo en el mapa",
  "splmap_tooltip_vehtab_veh_remove":              "Retire este veh&iacute;culo del panel",
  "splmap_tooltip_vehtab_veh_hideshow":            "Ocultar / Mostrar veh&iacute;culo en el mapa",
  "splmap_tooltip_vehtab_toggle_all":              "Alternar todos los veh&iacute;culos / grupos",
  "splmap_tooltip_vehtab_delete_all":              "Eliminar todos los veh&iacute;culos / grupos del panel",
  "splmap_tooltip_statustab_toggle_all":           "Alternar todos los estados",
  "splmap_tooltip_statustab_delete_all":           "Eliminar todos los estados",
  "splmap_tooltip_statustab_status_hideshow":      "Ocultar / Mostrar estado",
  "splmap_tooltip_statustab_status_remove":        "Eliminar este estado",
  "splmap_tooltip_exceptiontab_exception_remove":  "Eliminar esta excepci&oacute;n",
  "splmap_tooltip_exceptiontab_exception_hideshow":"Ocultar / Mostrar excepci&oacute;n",
  "splmap_tooltip_exceptiontab_toggle_all":        "Alternar todas las excepciones",
  "splmap_tooltip_exceptiontab_delete_all":        "Eliminar todas las excepciones",
  "splmap_tooltip_configpanel_open":               "Abrir panel de configuraci&oacute;n",
  "splmap_tooltip_configpanel_close":              "Cerrar el panel de configuraci&oacute;n",
  "splmap_configpanel_search":                     "Buscar...",
  "splmap_configpanel_vehtab_title":               "Veh&iacute;culos",
  "splmap_configpanel_vehtab_list_label":          "Veh&iacute;culos seleccionados",
  "splmap_configpanel_statustab_title":            "Estado",
  "splmap_configpanel_statustab_list_label":       "Estado seleccionado",
  "splmap_configpanel_exceptiontab_title":         "Excepciones",
  "splmap_configpanel_exceptiontab_list_label":    "Excepciones seleccionadas",
  "splmap_controlspanel_label_live":               "VIVO",
  "splmap_controlspanel_label_speed":              "Velocidad",
  "splmap_controlspanel_label_speed_tooltip":      "Men&uacute; de velocidad de reproducci&oacute;n (la velocidad no se puede cambiar en directo)",
  "splmap_controlspanel_label_date":               "Fecha",
  "splmap_controlspanel_label_time_start":         "Hora de inicio",
  "splmap_controlspanel_label_time_current":       "Tiempo actual",
  "splmap_controlspanel_tooltip_play":             "Jugar",
  "splmap_controlspanel_tooltip_pause":            "Pausa",
  "splmap_controlspanel_group":                    "Grupo",
  "splmap_map_zoom_in":                            "Acercarse",
  "splmap_map_zoom_out":                           "Disminuir el zoom",

  "error_spltools_notfound":                       "No se encontr&oacute; SpartanLync Tools Add-In. Instale y ejecute para habilitar las funciones de SpartanLync Temptrac / TPMS",
  "error_vehicle_cannot_fly":                      "Lo sentimos, no puedo volar hasta este veh&iacute;culo ... Vuelve a intentarlo en unos minutos.",
  "error_vehicle_no_gps":                          "Lo sentimos, no hay datos de GPS del d&iacute;a actual para este veh&iacute;culo.",
  "error_server_unavailable":                      "El servidor no est&aacute; disponible, int&eacute;ntelo de nuevo m&aacute;s tarde.",
  "error_not_enough_privs_to_switch":              "Error de SplMap: su cuenta MyGeotab no tiene permisos suficientes para permitir el cambio a SpartanLync Tools... Ejecute SpartanLync Tools manualmente.",
  "error_invalid_addin_array":                     "AddIn / customerPages Array no v&aacute;lido",
  "error_invalid_user":                            "Objeto de usuario no v&aacute;lido o no v&aacute;lido",
  "error_systemsettings_missing_invalid":          "Objeto SystemSettings faltante o no v&aacute;lido",

  "datepicker_date_in_future":                     "&iexcl;La fecha seleccionada es futura!",
  "datepicker_enter_to_apply_change":              "Por favor presione Enter para aplicar sus cambios.",
  "map_fetching_historical_data_inprogress":       "Obtenci&oacute;n de datos hist&oacute;ricos",
  "map_fetching_historical_data_completed":        "Carga de datos hist&oacute;ricos completa",

  "splgeotabmap_title":                            "Administrar SpartanLync para la instalaci&oacute;n de MyGeotab Map",
  "splgeotabmap_init_msg":                         "Comprobaci&oacute;n del estado de la instalaci&oacute;n",
  "splgeotabmap_success_msg":                      "Con &eacute;xito {op} SpartanLync {intofrom} MyGeotab Map",
  "splgeotabmap_install_btnlbl":                   "Instalar para todos",
  "splgeotabmap_uninstall_btnlbl":                 "Eliminar para todos",
  "splgeotabmap_my_account_disable":               "Eliminar solo mi cuenta",
  "splgeotabmap_my_account_enable":                "Habilitar para mi cuenta",
  "splgeotabmap_no_install_btnlbl":                "No puede {op} para todos",
  "splgeotabmap_no_install_btnsublbl":             "No hay suficientes privilegios ... Por favor, haga que el propietario / administrador de su base de datos use este bot&oacute;n",
  "splgeotabmap_addin_installed_msg":              "SpartanLync detectado como instalado en MyGeotab Map",
  "splgeotabmap_addIn_notinstalled_msg":           "SpartanLync NO est&aacute; instalado en MyGeotab Map",
  "splgeotabmap_failure_msg":                      "Error al {op} SpartanLync {tofrom} MyGeotab Map",
  "splgeotabmap_init_failure_msg":                 "Error al inicializar SpartanLync en MyGeotab Map",
  "splgeotabmap_err_fetch_userdata_msg":           "Faltan datos de la cuenta de usuario despu&eacute;s de obtener de la API de Geotab",
  "splgeotabmap_err_fetch_systemdata_msg":         "Faltan datos de configuraci&oacute;n del sistema despu&eacute;s de obtener de la API de Geotab",
  "splgeotabmap_feature_preview_enabled_foruser":  "SpartanLync en MyGeotab Map ya est&aacute; habilitado para [ {username} ]",
  "splgeotabmap_feature_preview_op_success_msg":   "{op} SpartanLync en MyGeotab Map para [ {username} ]",
  "splgeotabmap_feature_preview_op_failure_msg":   "Error al {op} SpartanLync en MyGeotab Map para el usuario [ {username} ]",

  "about_appname":                                 "SpartanLync Map",
  "about_instruction":                             "Use SpartanLync Tools para cambiar la configuraci&oacute;n anterior",
  "about_timezone":                                "Fecha y hora Zona horaria",
  "about_refresh":                                 "Frecuencia de actualizaci&oacute;n de la informaci&oacute;n del sensor",
  "about_lang":                                    "Idioma",
  "about_buildver":                                "Versi&oacute;n de compilaci&oacute;n",
  "about_builddate":                               "La fecha de construcci&oacute;n",
  "about_unknown":                                 "desconocido",
}
