/* eslint-disable */
if (typeof window.splmap == "undefined") {
  window.splmap = {
    lang: {}
  };
}
window.splmap.lang.es = {

  "veh_comp_tractor":                              "Tracto camión",
  "veh_comp_trailer1":                             "Remolque 1",
  "veh_comp_dolly":                                "Dolly",
  "veh_comp_trailer2":                             "Remolque 2",

  "sensor_search_busy_msg":                        "OCUPADO",
  "sensor_search_busy_getting_data_msg":           "Obteniendo datos",
  "sensor_search_last_reading":                    "&Uacute;ltima lectura",
  "sensor_search_back_in_time":                    "Viajando en el tiempo",
  "sensor_search_sensor_timestamp":                "Marca de tiempo del sensor",
  "sensor_search_switchto_spltools_instruction":   "Ver en SpartanLync Tools",
  "sensor_search_status_data_msg":                 "Datos de estado",

  "splmap_rule_name_label":                        "Nombre de la regla",
  "splmap_alert_header":                           "Alerta SpartanLync",
  "splmap_service_started":                        "El servicio SpartanLync Map se inici&oacute; correctamente",
  "splmap_service_failed":                         "Error al iniciar el servicio SpartanLync Map",
  "splmap_veh_flying_msg":                         "Localizando al evehículo<br />'{veh}'",
  "splmap_veh_flying_loading_gps":                 "Carga de datos de GPS del veh&iacute;culo",
  "splmap_veh_flying_loading_gps_subtitle":        "Localizando....",
  "splmap_vehpanel_component_title":               "Componentes del veh&iacute;culo",
  "splmap_vehpanel_splsensors_btn_tooltip":        "Ver datos del sensor SpartanLync para este veh&iacute;culo",

  "splmap_tooltip_map_add_veh_tofilter":           "Agregar dispositivo al filtro de veh&iacute;culos",
  "splmap_tooltip_vehtab_veh_flyto":               "Localizar el vehículo en el mapa",
  "splmap_tooltip_vehtab_veh_remove":              "Retire este veh&iacute;culo del panel",
  "splmap_tooltip_vehtab_veh_hideshow":            "Ocultar / Mostrar veh&iacute;culo en el mapa",
  "splmap_tooltip_vehtab_toggle_all":              "Alternar todos los veh&iacute;culos / grupos",
  "splmap_tooltip_vehtab_delete_all":              "Eliminar todos los veh&iacute;culos / grupos del panel",
  "splmap_tooltip_statustab_toggle_all":           "Alternar todos los estados",
  "splmap_tooltip_statustab_delete_all":           "Eliminar todos los estados",
  "splmap_tooltip_statustab_status_hideshow":      "Ocultar / Mostrar estado",
  "splmap_tooltip_statustab_status_remove":        "Eliminar este estado",
  "splmap_tooltip_exceptiontab_exception_remove":  "Eliminar esta excepci&oacute;n",
  "splmap_tooltip_exceptiontab_exception_hideshow":"Ocultar / Mostrar excepci&oacute;n",
  "splmap_tooltip_exceptiontab_toggle_all":        "Alternar todas las excepciones",
  "splmap_tooltip_exceptiontab_delete_all":        "Eliminar todas las excepciones",
  "splmap_tooltip_configpanel_open":               "Abrir panel de configuraci&oacute;n",
  "splmap_tooltip_configpanel_close":              "Cerrar el panel de configuraci&oacute;n",
  "splmap_configpanel_search":                     "Buscar...",
  "splmap_configpanel_vehtab_title":               "Veh&iacute;culos",
  "splmap_configpanel_vehtab_list_label":          "Veh&iacute;culos seleccionados",
  "splmap_configpanel_statustab_title":            "Estado",
  "splmap_configpanel_statustab_list_label":       "Estado seleccionado",
  "splmap_configpanel_exceptiontab_title":         "Excepciones",
  "splmap_configpanel_exceptiontab_list_label":    "Excepciones seleccionadas",
  "splmap_controlspanel_label_live":               "EN VIVO",
  "splmap_controlspanel_label_live_help":          "( Haga clic para volver a VIVO )",
  "splmap_controlspanel_label_speed":              "Velocidad",
  "splmap_controlspanel_label_speed_tooltip":      "Menú de velocidad de reproducción (la velocidad no se puede cambiar en tiempo real)",
  "splmap_controlspanel_label_date":               "Fecha",
  "splmap_controlspanel_label_time_start":         "Hora de inicio",
  "splmap_controlspanel_label_time_current":       "Tiempo actual",
  "splmap_controlspanel_label_apply_changes_btn":  "aplicar",
  "splmap_controlspanel_tooltip_play":             "Reproducir",
  "splmap_controlspanel_tooltip_pause":            "Pausa",
  "splmap_controlspanel_group":                    "Grupo",
  "splmap_map_zoom_in":                            "Acercar",
  "splmap_map_zoom_out":                           "Alejar",

  "error_spltools_notfound":                       "No se encontr&oacute; SpartanLync Tools Add-In. Instale y ejecute para habilitar las funciones de SpartanLync Temptrac / TPMS",
  "error_vehicle_cannot_fly":                      "Lo sentimos, no puedo volar hasta este veh&iacute;culo ... Vuelve a intentarlo en unos minutos.",
  "error_vehicle_no_gps":                          "Lo sentimos, no hay datos de GPS del d&iacute;a actual para este veh&iacute;culo",
  "error_vehicle_no_gps_click_show_btn_to_view":   "Lo sentimos, no hay datos de GPS del día actual para este vehículo. Haga clic en el botón Ocultar / Mostrar para ver el vehículo en el mapa",
  "error_server_unavailable":                      "El servidor no est&aacute; disponible, int&eacute;ntelo de nuevo m&aacute;s tarde.",
  "error_not_enough_privs_to_switch":              "Error de SplMap: su cuenta MyGeotab no tiene permisos suficientes para permitir el cambio a SpartanLync Tools... Ejecute SpartanLync Tools manualmente.",
  "error_invalid_addin_array":                     "AddIn / customerPages Array no v&aacute;lido",
  "error_invalid_user":                            "Usuario no válido",
  "error_systemsettings_missing_invalid":          "Objeto SystemSettings faltante o no v&aacute;lido",

  "datepicker_enter_to_apply_change":              "En la ventana emergente, presione ENTER para aplicar su cambio de hora",
  "datepicker_date_in_future":                     "&iexcl;La fecha seleccionada es futura!",
  "map_fetching_historical_data_inprogress":       "Obtenci&oacute;n de datos hist&oacute;ricos",
  "map_fetching_historical_data_completed":        "Carga de datos hist&oacute;ricos completa",

  "splgeotabmap_title":                            "Administrar SpartanLync para la instalaci&oacute;n de MyGeotab Map",
  "splgeotabmap_init_msg":                         "Comprobaci&oacute;n del estado de la instalaci&oacute;n",
  "splgeotabmap_success_msg":                      "Con &eacute;xito {op} SpartanLync {intofrom} MyGeotab Map",
  "splgeotabmap_install_btnlbl":                   "Instalar para todos",
  "splgeotabmap_uninstall_btnlbl":                 "Eliminar para todos",
  "splgeotabmap_my_account_disable":               "Eliminar solo mi cuenta",
  "splgeotabmap_my_account_enable":                "Habilitar para mi cuenta",
  "splgeotabmap_no_install_btnlbl":                "No puede {op} para todos",
  "splgeotabmap_no_install_btnsublbl":             "No hay suficientes privilegios ... Por favor, solicite al administrador de su base de datos use este botón o le otorgue los privilegios adecuados",
  "splgeotabmap_addin_installed_msg":              "SpartanLync detectado como instalado en MyGeotab Map",
  "splgeotabmap_addIn_notinstalled_msg":           "SpartanLync NO est&aacute; instalado en MyGeotab Map",
  "splgeotabmap_failure_msg":                      "Error al {op} SpartanLync {tofrom} MyGeotab Map",
  "splgeotabmap_init_failure_msg":                 "Error al inicializar SpartanLync en MyGeotab Map",
  "splgeotabmap_err_fetch_userdata_msg":           "Faltan datos de la cuenta de usuario en la API de Geotab",
  "splgeotabmap_err_fetch_systemdata_msg":         "Faltan datos de configuración del sistema en la API de Geotab",
  "splgeotabmap_feature_preview_enabled_foruser":  "SpartanLync en MyGeotab Map ya est&aacute; habilitado para [ {username} ]",
  "splgeotabmap_feature_preview_op_success_msg":   "{op} SpartanLync en MyGeotab Map para [ {username} ]",
  "splgeotabmap_feature_preview_op_failure_msg":   "Error al {op} SpartanLync en MyGeotab Map para el usuario [ {username} ]",
  "splgeotabmap_consent_install_msg":              "Obtenga información del sensor SpartanLync en MyGeotab Map para todos los usuarios dentro de esta base de datos eligiendo la siguiente opción de instalación.",
  "splgeotabmap_consent_uninstall_msg":            "Puede eliminar SpartanLync de MyGeotab Map en cualquier momento desde el menú del icono SpartanLync.",
  "splgeotabmap_consent_btn_label_install":        "Instalar en MyGeotab Map",
  "splgeotabmap_consent_btn_label_skip":           "Ahora no",

  "about_appname":                                 "SpartanLync Map",
  "about_instruction":                             "Use SpartanLync Tools para cambiar la configuraci&oacute;n anterior",
  "about_timezone":                                "Fecha y hora (Zona horaria)",
  "about_refresh":                                 "Frecuencia de actualizaci&oacute;n de la informaci&oacute;n del sensor",
  "about_lang":                                    "Idioma",
  "about_buildver":                                "Versi&oacute;n de compilaci&oacute;n",
  "about_builddate":                               "Fecha de creación",
  "about_unknown":                                 "desconocido",

  // Fault Alerts
  "alert_tooltip":                                 "{alert_msg}<br />en<br />{timestamp}",
  "alert_header":                                  "Alerta post-ignición",
  "alert_header_red":                              "Alerta roja",
  "alert_header_amber":                            "Alerta Ambar",
  "alert_sensor_location_header":                  "Ubicación del sensor",
  "alert_missing_sensor":                          "Sensor faltante",
  "alert_temperature_over":                        "Exceso de temperatura",
  "alert_temp_extreme_low":                        "Temperatura extremadamente baja",
  "alert_temp_extreme_high":                       "Temperatura extremadamente alta",
  "leak_detected":                                 "Fuga detectada",
  "alert_pressure_extreme_over":                   "Sobrepresión extrema",
  "alert_pressure_extreme_under":                  "Presión extrema",
  "alert_pressure_over":                           "Sobrepresión",
  "alert_pressure_under":                          "Bajo presión",
  "alert_battery_low_voltage":                     "La batería del vehículo tiene BAJO voltaje",
  "alert_tire_temperature_fault":                  "Fallo de temperatura de los neumáticos",
  "alert_tire_pressure_fault":                     "Fallo de presión de los neumáticos",
  "alert_temptrac_fault":                          "Fallo TempTrac",
  "alert_desc_zone":                               "Zona",
  "alert_desc_axle":                               "Eje",
  "alert_desc_tire":                               "Neum&aacute;tico",
  "alert_desc_tractor":                            "Tractor",
  "alert_desc_trailer":                            "Remolque",
  "alert_desc_dolly":                              "Muñequita",
}
